name: Upstream

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          mamba-version: '*'
          environment-file: ci/minimum-tests.yml
          activate-environment: xskillscore-minimum-tests
          auto-activate-base: false

      - name: Build environment
        run: |
          mamba env update -f ci/minimum-tests.yml

      - name: Install upstream packages
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/pydata/xarray.git
          python -m pip install git+https://github.com/dask/dask.git
          python -m pip install git+https://github.com/xgcm/xhistogram.git 

      - name: Install
        shell: bash -l {0}
        run: python -m pip install -e .

      - name: List installed packages
        shell: bash -l {0}
        run: conda list

      - name: Run tests
        run: |
          pytest -n 4 --cov=xskillscore --cov-report=xml --verbose

      - name: Coverage
        uses: codecov/codecov-action@v1